	--ACERVO
	SELECT 
		DISTINCT 
		PROCESSO.NUMEROPROCESSOUNICO as numeroprocesso, 
		ARQUIVO_DOCUMENTO.CODARQUIVO AS idprocessodocumento,
		ARQUIVO_DOCUMENTO.DATAINSERCAO AS dtjuntada,
		DESCRICAO_TIPO_ARQUIVO.DESCRICAO AS dstipoprocessodocumento,  
		ARQUIVO_DOCUMENTO.CAMINHO AS nrdocumentostorage,
		'https://projudi.tjba.jus.br/projudi/listagens/DadosProcesso?numeroProcesso=' || to_char(PROCESSO.numeroprocesso) as linkProcesso,
		UPPER(VARA.DESCRICAO) AS orgaojulgador,
		UPPER(COMARCA.DESCRICAO) AS jurisdicao,
		PROCESSO.DATARECEBIMENTO AS dataautuacao,
		UPPER(TIPO_ACAO.DESCRICAO) AS classe,
		(SELECT DISTINCT LISTAGG(UPPER(MOVIMENTACAO.CODDESCREVEMOVIMENTACAO||';'||MOVIMENTACAO.DESCRICAO||';'||ARQUIVO_DOCUMENTO.CODARQUIVO||';'||ARQUIVO_DOCUMENTO.DATAINSERCAO||';'||DESCRICAO_TIPO_ARQUIVO.DESCRICAO||';'||ARQUIVO_DOCUMENTO.CAMINHO), ';')
	   	  		 WITHIN GROUP (ORDER BY MOVIMENTACAO.CODDESCREVEMOVIMENTACAO)
		      FROM ECNJ.MOVIMENTACAO, ECNJ.ARQUIVO_DOCUMENTO, ECNJ.DESCRICAO_TIPO_ARQUIVO
	 	     WHERE ARQUIVO_DOCUMENTO.CODIGOTIPOARQUIVO = DESCRICAO_TIPO_ARQUIVO.CODIGO
		 	   AND MOVIMENTACAO.CODDOCUMENTO = ARQUIVO_DOCUMENTO.CODDOCUMENTO
	 	       AND MOVIMENTACAO.NUMEROPROCESSO = PROCESSO.NUMEROPROCESSO 
	 	       AND MOVIMENTACAO.STATUS = 0
	 	       AND MOVIMENTACAO.CODRECURSO IS NULL
		       AND MOVIMENTACAO.CODDESCREVEMOVIMENTACAO IN (SELECT M.SEQ_CATEGORIA
				                                         	 FROM ECNJ.CNJ_MOVIMENTACAO_CATEGORIA M
				                                        --   WHERE M.SEQ_CATEGORIA not in ('10953','196','198', '200', '871')
				                                           START WITH M.SEQ_CATEGORIA IN ('193') 
				                                           CONNECT BY PRIOR M.SEQ_CATEGORIA = M.SEQ_CATEGORIA_PAI) 
		       AND MOVIMENTACAO.CODDOCUMENTO = (SELECT MIN(M2.CODDOCUMENTO) --  SELECT * FROM ECNJ.MOVIMENTACAO WHERE CODDOCUMENTO IN (159620531,67816084)
				                                  FROM ECNJ.MOVIMENTACAO M2 -- 
				                                 WHERE M2.NUMEROPROCESSO = PROCESSO.NUMEROPROCESSO 
				                                   AND M2.STATUS = 0
				                                   AND M2.CODRECURSO IS NULL
												   AND M2.CODDESCREVEMOVIMENTACAO IN  ('244','465','11396','198','455','2013','11407','11796','218','235','457','459','462','11374','853','450','1042','1046',
																						'1047','12028','11403','11795','11877','461','463','10953','210','444','452','220','466','901','1050','11878','193',
																						'230','464','11377','11379','11380','240','1043','1044','11879','456','11373','11394','212','447','449','453','239',
																						'242','972','11411','10964','11876','473','11376','10961','200','443','445','214','451','238','241','471','900','973',
																						'1048','11401','11405','236','454','458','460','385','202','442','446','221','871','884','1045','11801','11402','11404',
																						'11408','11409','11378','11381','10965','448','219','237','1049','11406','12187' )
											)
			                                          
		) AS julgamento 
	FROM 
		ECNJ.MOVIMENTACAO MOV_DISTRIBUICAO,
		ECNJ.PROCESSO,
		ECNJ.ARQUIVO_DOCUMENTO,
		ECNJ.DESCRICAO_TIPO_ARQUIVO, 
		ECNJ.AREADEVARAS,
		ECNJ.VARA,
		ECNJ.COMARCA ,
		ECNJ.TIPO_ACAO
	WHERE MOV_DISTRIBUICAO.NUMEROPROCESSO = PROCESSO.NUMEROPROCESSO
	AND MOV_DISTRIBUICAO.CODDOCUMENTO = ARQUIVO_DOCUMENTO.CODDOCUMENTO
	AND ARQUIVO_DOCUMENTO.CODIGOTIPOARQUIVO = DESCRICAO_TIPO_ARQUIVO.CODIGO
	AND PROCESSO.COD_AREA = AREADEVARAS.COD_AREA AND AREADEVARAS.COD_AREA = ?
	AND PROCESSO.COD_VARA = VARA.COD_VARA
	AND PROCESSO.TIPOACAO = TIPO_ACAO.CODTIPOACAO
	AND VARA.CODCOMARCA = COMARCA.CODCOMARCA
	AND ARQUIVO_DOCUMENTO.CONTENTTYPE = 'application/pdf'
	AND DESCRICAO_TIPO_ARQUIVO.CODIGO = 30 -- PETICAO_INICIAL
	AND PROCESSO.DATAARQUIVAMENTO IS NULL
	AND PROCESSO.COD_VARA = ?
	AND MOV_DISTRIBUICAO.CODDESCREVEMOVIMENTACAO = 981 -- MOV RECEBIDO PELO DISTRIBUIDOR (ONDE FICA A PET INI)
	AND PROCESSO.SEGREDOJUSTICA = 0 -- (se for gerar dataset descomentar esta linha)
	--AND NOT EXISTS
	--(
	--	SELECT 1 FROM ECNJ.PROCESSO p2 
	--	INNER JOIN ECNJ.LOCALIZADOR_PROCESSO ON LOCALIZADOR_PROCESSO.NUMEROPROCESSO = p2.NUMEROPROCESSO
	--	INNER JOIN ECNJ.TIPO_LOCALIZADOR ON TIPO_LOCALIZADOR.CODLOCALIZADOR = LOCALIZADOR_PROCESSO.CODLOCALIZADOR
	--	AND TIPO_LOCALIZADOR.DESCRICAO  LIKE 'IA_%'
	--	WHERE  p2.NUMEROPROCESSO= PROCESSO.NUMEROPROCESSO 
	--	AND TIPO_LOCALIZADOR.codvara = 0
	--	AND LOCALIZADOR_PROCESSO.DATAFECHAMENTO IS NULL
	--)
	AND rownum < 1000