package MODEL;

public enum Acao {
	
	BAIXAR_PROCESSO,
	BAIXAR_PROCESSO_PARTES_INTIMADAS_DIARIO_SISTEMA,
	REINTIMAR_PARTES_PROCESSO,
	DISPENSAR_NEM_TODAS_PARTES_TEM_DECURSO,
	DISPENSAR_MOVIMENTACAO_NAO_PERMITIDA,
	DISPENSAR_BAIXA_DEFINITIVA,
	DISPENSAR_NAO_EXISTENCIA_ACORDAO,
	HUMANO_ANALISAR,
	CONCLUSO_EMBARGOS_DECLARACAO, 
	CONCLUSO_EMBARGOS_EXECUCAO,
	ENVIO_TARE,
	NAO_PROSSEGUIR_PARTE_AINDA_NO_PRAZO_DE_MANIFESTACAO,
	NAO_PROSSEGUIR_EXISTENCIA_DE_PETICAO_INTERMEDIARIA,
	CHAMAR_SINAPSES_PARA_DESCOBRIR_TIPO_DE_PETICAO;
}
