package MODEL;

public enum Etiqueta {
	
	LICENCA_PREMIO,
	ABONO_PECUNIARIO,
	ABONO_PERMANENCIA,
	DIVISOR_200,
	COELBA_LUZ_PARA_TODOS,
	COELBA_TARIFA_RURAL,
	FERIAS_NAO_GOZADAS,
	BANCOS_EMPRESTIMO,
	COELBA_APAGAO,
	MEDIA_CONSUMO,
	EMBASA_ROMPIMENTO_ADUTORA,
	COELBA_SUSPENSAO_FORNECIMENTO,
	EMBASA_MA_PRESTACAO_SERVICO,
	EMBASA_SUSPENSAO_DO_FORNECIMENTO,
	NEGATIVACAO_INDEVIDA,
	EMPRESAS_AEREAS_ATRASO,
	EMPRESAS_AEREAS_CANCELAMENTO,
	EMPRESAS_AEREAS_EXTRAVIO_DANO_BAGAGEM,
	EMPRESAS_AEREAS_OVERBOOKING,
	EMPRESAS_AEREAS_PROGRAMA_MILHAGEM,
	PLANO_DE_SAUDE_REAJUSTE_ANUAL,
	VICIO_DE_PRODUTO,
	PRODUTO_ATRASO_ENTREGA,
	PLANO_DE_SAUDE_CANCELAMENTO,
	PLANO_DE_SAUDE_REAJUSTE_SINISTRALIDADE,
	TELEFONIA_INSTABILIDADE,
	TELEFONIA_COBRANCA_INDEVIDA,
	TELEFONIA_PORTABILIDADE,
	PLANO_DE_SAUDE_NEGATIVA_PROCEDIMENTO,
	PLANO_DE_SAUDE_REAJUSTE_FAIXA_ETARIA,
	BANCOS_EMPRESTIMO_DECADENCIA_QUADRIENAL,
	INCOMPETENCIA_TERRITORIAL_RECOMENDACAO_02,
	SERVIDOR_PROGRESSAO,
	OUTROS;
	
	
}
