SELECT 
	distinct R.NUMEROPROCESSOUNICO AS numeroProcesso,
	R.NUMEROPROCESSO AS idProcesso,
	M.DATARECEBIMENTO AS dataMovimentacao,
	M.CODDESCREVEMOVIMENTACAO AS codMovimentoCNJ,
	M.DESCRICAO AS descMovimentoCNJ,
	M.DESCRICAO AS textoFinalMovimento,
	dta.CODIGO AS tipoDocumento,
	dta.DESCRICAO AS descDocumento
	
FROM ECNJ.RECURSO R 
INNER JOIN ECNJ.MOVIMENTACAO M ON R.NUMEROPROCESSO = M.NUMEROPROCESSO
							AND M.DATARECEBIMENTO >= (
									select max(M2.DATARECEBIMENTO) from ECNJ.MOVIMENTACAO M2 
									WHERE M2.NUMEROPROCESSO = R.NUMEROPROCESSO
									AND M2.CODDESCREVEMOVIMENTACAO in (237,238,239,240,241,242,901)
							)
LEFT JOIN ECNJ.ARQUIVO_DOCUMENTO AD ON M.CODDOCUMENTO = AD.CODDOCUMENTO
LEFT JOIN ECNJ.DESCRICAO_TIPO_ARQUIVO DTA ON AD.CODIGOTIPOARQUIVO = DTA.CODIGO
WHERE R.NUMEROPROCESSOUNICO IN 
(
SELECT Recurso.NUMEROPROCESSOUNICO 
	FROM ecnj.Movimentacao, ecnj.Intimacao, ecnj.Recurso, ecnj.Partes_Processo, ecnj.Parte, ecnj.Prazo
	WHERE Movimentacao.CODDOCUMENTO = Intimacao.CODDOCUMENTO
	AND Recurso.CODRECURSO = Movimentacao.CODRECURSO
	AND Partes_Processo.CODPARTEPROCESSO = Intimacao.CODPARTEPROCESSO
	AND Parte.CODPARTE = Partes_Processo.CODPARTE
	AND Intimacao.CODPRAZO = Prazo.CODPRAZO
	AND Intimacao.DATAANALISEDECURSOPRAZO IS NULL
	AND Intimacao.DATACERTIDAO IS NOT NULL
	AND Intimacao.CODTURMA = ?
	
	
) 
