SELECT 
	distinct R.NUMEROPROCESSOUNICO AS numeroProcesso,
	PARTE.NOME AS nomeParte
FROM ECNJ.RECURSO R 
INNER JOIN ECNJ.PARTE_RECURSO PR ON R.CODRECURSO = PR.CODRECURSO AND PR.DATABAIXA IS NULL 
INNER JOIN ECNJ.PARTES_PROCESSO PP ON PR.CODPARTEPROCESSO = PP.CODPARTEPROCESSO AND PP.DATABAIXA IS NULL
INNER JOIN ECNJ.PARTE PARTE ON PP.CODPARTE = PARTE.CODPARTE
WHERE R.NUMEROPROCESSOUNICO IN 
(
	SELECT Recurso.NUMEROPROCESSOUNICO 
	FROM ecnj.Movimentacao, ecnj.Intimacao, ecnj.Recurso, ecnj.Partes_Processo, ecnj.Parte, ecnj.Prazo
	WHERE Movimentacao.CODDOCUMENTO = Intimacao.CODDOCUMENTO
	AND Recurso.CODRECURSO = Movimentacao.CODRECURSO
	AND Partes_Processo.CODPARTEPROCESSO = Intimacao.CODPARTEPROCESSO
	AND Parte.CODPARTE = Partes_Processo.CODPARTE
	AND Intimacao.CODPRAZO = Prazo.CODPRAZO
	AND Intimacao.DATAANALISEDECURSOPRAZO IS NULL
	AND Intimacao.DATACERTIDAO IS NOT NULL
	AND Intimacao.CODTURMA =?
	
) 